### ISSUE TITLE
CUDA, CUDNN, and CUBLAS versions

### ISSUE THREAD

**Issue by AjinkyaBankar** [tigercosmos/simple-vgg16-cu#1]
Hi Liu,
Can you please share CUDA, CUDNN, and CUBLAS versions required for compiling the code? Thanks.

**Comment by tigercosmos** [comment]
@AjinkyaBankar  I forgot it. I thought it's about CUDA 10 or 11, CUDNN 7
The latest version should work. If there are errors, please refer to the NVIDIA API documents.
